// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.1
// source: scanner.proto

package scannerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortScannerClient is the client API for PortScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortScannerClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type portScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewPortScannerClient(cc grpc.ClientConnInterface) PortScannerClient {
	return &portScannerClient{cc}
}

func (c *portScannerClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/scanner.PortScanner/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortScannerServer is the server API for PortScanner service.
// All implementations must embed UnimplementedPortScannerServer
// for forward compatibility
type PortScannerServer interface {
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedPortScannerServer()
}

// UnimplementedPortScannerServer must be embedded to have forward compatible implementations.
type UnimplementedPortScannerServer struct {
}

func (UnimplementedPortScannerServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedPortScannerServer) mustEmbedUnimplementedPortScannerServer() {}

// UnsafePortScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortScannerServer will
// result in compilation errors.
type UnsafePortScannerServer interface {
	mustEmbedUnimplementedPortScannerServer()
}

func RegisterPortScannerServer(s grpc.ServiceRegistrar, srv PortScannerServer) {
	s.RegisterService(&PortScanner_ServiceDesc, srv)
}

func _PortScanner_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortScannerServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.PortScanner/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortScannerServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortScanner_ServiceDesc is the grpc.ServiceDesc for PortScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scanner.PortScanner",
	HandlerType: (*PortScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _PortScanner_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scanner.proto",
}
